site_name: Ligato Documentation
repo_url: https://github.com/chrismetz09/ligato-docs

theme: readthedocs

site_url: https://ligato-docs.readthedocs.io/en/latest/

nav:
    - About Ligato Documentation: index.md
    - CNF: CNF/CNF-definition.md
    - CN Infra: Infra/cn-toc-file.md 
    - VPP Agent: user-guide/User-Guide.md
    - Tutorials: tutorials/README.md
